In [1]:
3 + 5 * 4

23

In [2]:
weight_kg = 60

In [3]:
weight_kg_text = "weight in kilograms:"

In [4]:
print(weight_kg_text, weight_kg)

weight in kilograms 60


In [5]:
print("Weight in pounds", weight_kg*2.2)

Weight in pounds 132.0


In [7]:
x = 5
y = 6
print(x+y)
x = y
print (x+y)

11
12


In [8]:
47.5*5

237.5

In [9]:
mass = 47.5
age = 122
mass = mass * 5
age = age - 10
print(mass,age)

237.5 112


In [12]:
first, second = 'Grace' , 'Shawn'
print(first,second, first)

Grace Shawn Grace


In [2]:
import numpy


In [3]:
numpy.loadtxt(fname = 'inflammation-01.csv', delimiter = ',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [4]:
medical_data = numpy.loadtxt(fname = 'inflammation-01.csv', delimiter = ',')

In [5]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [6]:
print(type(medical_data))

<class 'numpy.ndarray'>


In [7]:
#rows, cols
print(medical_data.shape)

(54, 40)


In [8]:
colors = ['red', 'green', 'blue']

In [9]:
print(colors[0, 2])

TypeError: list indices must be integers or slices, not tuple

In [10]:
print('first value in medical data:', medical_data[0,0])

first value in medical data: 0.0


In [11]:
print(medical_data(0,0))

TypeError: 'numpy.ndarray' object is not callable

In [12]:
print(medical_data.shape)

(54, 40)


In [13]:
med_data_shape = medical_data.shape
print(med_data_shape)

(54, 40)


In [14]:
middle_of_rows = int(med_data_shape[0]/2)
middle_of_cols = int(med_data_shape[1]/2)
print(middle_of_rows, middle_of_cols)
middle value of medical data: ',medical_data[middle_of_rows, middle_of_cols]'

SyntaxError: invalid syntax (<ipython-input-14-bc2f07bd189a>, line 4)

In [15]:
##slicing data
#I want to grab everything from first item up to but not including the last item listed
print(medical_data[0:4,0:10])

print(medical_data[5:10, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]
[[0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [16]:
import time
print(time.ctime())

Wed Jan 29 12:40:47 2020


In [17]:
import numpy as np
meanval, stdval = np.mean(medical_data), np.std(medical_data)
print(meanval, ',', stdval)

5.658333333333333 , 4.352194529455482


In [41]:
len(medical_data)

54

In [43]:
patient_1 = medical_data[0, :]
print(patient_1)

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [44]:
print(patient_1[1])

0.0


In [45]:
max_infl_pt1 = np.max(patient_1)
print('max inflammation for patient 1:' , max_infl_pt1)

max inflammation for patient 1: 18.0


In [48]:
print(np.mean(medical_data, axis = 0))

[ 0.          0.66666667  1.33333333  2.33333333  2.          1.66666667
  4.33333333  3.66666667  5.          6.          6.          7.
  6.33333333  6.33333333  5.          7.66666667  6.33333333 11.33333333
  9.66666667 11.33333333 14.33333333 10.33333333 11.66666667 11.
  8.66666667  8.66666667  8.66666667  6.          7.66666667  4.33333333
  5.66666667  4.66666667  4.33333333  4.33333333  3.33333333  4.
  1.66666667  2.          0.33333333  0.66666667]


In [61]:
def hello_person(name):
    print('Hello', name)

In [62]:
hello_person('robert')

Hello robert


In [63]:
def square_numbers(x):
    square = x*x
    return(square)

In [64]:
square_numbers(10)

100

In [65]:
sq10 = square_numbers(10)

In [66]:
print(x)

6


In [67]:
5**3

125

In [68]:
def pp(base, exponent):
    return(base**exponent)

In [69]:
pp(5,2)

25